I'm sorry, but an uncaught exception occurred.

While executing init code:
  File "game/dungeonBattle.rpy", line 1, in script
    init python:
  File "game/dungeonBattle.rpy", line 5, in <module>
    import summonersRift
ImportError: No module named summonersRift

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/dungeonBattle.rpy", line 1, in script
    init python:
  File "/home/digiholic/workspace/SummonerSweetheart-0.9-all/renpy/ast.py", line 785, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/digiholic/workspace/SummonerSweetheart-0.9-all/renpy/python.py", line 1382, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/dungeonBattle.rpy", line 5, in <module>
    import summonersRift
ImportError: No module named summonersRift

Linux-3.16.0-41-generic-x86_64-with-debian-jessie-sid
Ren'Py 6.18.3.761
Summoner Sweetheart 0.9
