I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script00.rpy", line 501, in script call
    call dungeon
  File "game/script00.rpy", line 582, in script call
    call screen dungeon_run(True)
  File "game/scriptDungeon.rpy", line 152, in script call
    call screen dungeon_run(True)
  File "game/scriptDungeon.rpy", line 226, in script call
    call screen dungeon_run(True)
  File "game/scriptDungeon.rpy", line 249, in script
    $ current_battle.oneOnOne()
  File "game/scriptDungeon.rpy", line 249, in <module>
    $ current_battle.oneOnOne()
  File "game/dungeonBattle.rpy", line 498, in oneOnOne
    if len(self.enemies > 1):
TypeError: object of type 'bool' has no len()

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script00.rpy", line 501, in script call
    call dungeon
  File "game/script00.rpy", line 582, in script call
    call screen dungeon_run(True)
  File "game/scriptDungeon.rpy", line 152, in script call
    call screen dungeon_run(True)
  File "game/scriptDungeon.rpy", line 226, in script call
    call screen dungeon_run(True)
  File "game/scriptDungeon.rpy", line 249, in script
    $ current_battle.oneOnOne()
  File "/home/digiholic/workspace/SummonerSweetheart-0.9-all/renpy/ast.py", line 785, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/digiholic/workspace/SummonerSweetheart-0.9-all/renpy/python.py", line 1382, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/scriptDungeon.rpy", line 249, in <module>
    $ current_battle.oneOnOne()
  File "game/dungeonBattle.rpy", line 498, in oneOnOne
    if len(self.enemies > 1):
TypeError: object of type 'bool' has no len()

Linux-3.16.0-41-generic-x86_64-with-debian-jessie-sid
Ren'Py 6.18.3.761
Summoner Sweetheart 0.9
