I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script00.rpy", line 558, in script call
    call dungeon
  File "game/script00.rpy", line 622, in script call
    call screen dungeon_run()
  File "game/script00.rpy", line 681, in script
    scene expression DungeionScene()
  File "game/script00.rpy", line 681, in <module>
    scene expression DungeionScene()
NameError: name 'DungeionScene' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script00.rpy", line 558, in script call
    call dungeon
  File "game/script00.rpy", line 622, in script call
    call screen dungeon_run()
  File "game/script00.rpy", line 681, in script
    scene expression DungeionScene()
  File "/home/digiholic/workspace/SummonerSweetheart-0.9-all/renpy/ast.py", line 1120, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "/home/digiholic/workspace/SummonerSweetheart-0.9-all/renpy/ast.py", line 997, in show_imspec
    expression = renpy.python.py_eval(expression)
  File "/home/digiholic/workspace/SummonerSweetheart-0.9-all/renpy/python.py", line 1416, in py_eval
    return eval(py_compile(source, 'eval'), globals, locals)
  File "game/script00.rpy", line 681, in <module>
    scene expression DungeionScene()
NameError: name 'DungeionScene' is not defined

Linux-3.11.0-26-generic-x86_64-with-debian-wheezy-sid
Ren'Py 6.18.3.761
Summoner Sweetheart 0.9
